<div id="sendmessage-form">

    <form class="form sendmessage"

          action="<?php echo $this->getUrl('androidservices/tabletmessaging/submitmessage'); ?>"

          id="sendmessage-form"

          method="post"

          data-hasrequired="<?php  echo __('* Required Fields') ?>"

          data-mage-init='{"validation":{}}' >

        <input type="hidden" name="form_key"  value="<?php /* @escapeNotVerified */ echo $this->getFormKey(); ?>" />

        <fieldset class="fieldset">

<!--            <legend class="legend"><span>--><?php // echo __("Message Type") ?><!--</span></legend><br />-->

            <div class="field message_type required">

                <label class="label" for="message_type"><span><?php  echo __('Message Type') ?></span></label>

                <div class="control">
                    <?php $messageTypes = $this->getMessageTypeConfig();

                    ?>
                    <select name="message_type" id="message_type"  data-validate="{required:true, 'validate-select':true}">
                        <option value=""> </option>
                        <?php foreach ($messageTypes as $messageType => $value){ ?>
                            <option value="<?php echo $messageType ?>"><?php echo $value ?></option>
                        <?php } ?>

                    </select>

                </div>

            </div>
            <br>
            <div class="field reciepient required">

                <label class="label" for="reciepient"><span><?php echo __('Reciepient') ?></span></label>

                <div class="control">
                    <?php $tabletUsers = $this->tabletUsers(); ?>
                    <select id='reciepient' name="reciepient[]" multiple style="width:300px" data-validate="{required:true, 'validate-select':true}">
                        <?php
                        foreach ($tabletUsers as $tabletUser){ ?>
                            <option value="<?php echo $tabletUser ?>"><?php echo $tabletUser ?></option>
                        <?php } ?>
                    </select>

                </div>

            </div>
            <br>

            <div class="field comment required">

                <label class="label" for="message"><span><?php  echo __('Message') ?></span></label>

                <div class="control">

                    <textarea name="message" id="message" title="<?php  echo __('Message') ?>" class="input-text" cols="40" rows="10" data-validate="{required:true}"></textarea>

                </div>

            </div>
            <br>
        </fieldset>
        <br>
        <div class="actions-toolbar">

            <div class="primary">

                <button type="submit" title="<?php  echo __('Submit Message') ?>" class="action submit primary" id="submit_message">

                    <span><?php  echo __('Submit Message') ?></span>

                </button>

            </div>

        </div>

    </form>

</div>

<script type="text/javascript">
    require(["jquery",'TM_AndroidServices/js/dropdown.min'],function($,select2){
        
        $("#reciepient").select2({
            minimumResultsForSearch: Infinity
        });

        

        $("#message_type").change(function(){
          if(this.value === "announcement"){
            $('#reciepient').prop('disabled', true);
          }else{
            $('#reciepient').prop('disabled', false);
          }

        });

    });
</script>